### ISSUE TITLE
Add support for using AppRole credentials

### ISSUE THREAD

**Issue by FWest98** [ngrewe/vault-ssh-renew#1]
Vault supports authentication using [Approle](https://www.vaultproject.io/docs/auth/approle), which is useful for automatically provisioned machines using e.g. Terraform (example [instructions](https://learn.hashicorp.com/tutorials/vault/approle-trusted-entities?in=vault/auth-methods)), as well as being useful in general to prevent having to work with individual tokens.

It would be very nice to see incorporation of authentication using AppRole in this tool.

**Comment by ngrewe** [comment]
Hi Floris! 

Thanks for your question and my apologies for taking a while to getting around to respond. I'm a bit reluctant to add features around managing Vault tokens because that seems to be something that differs a lot from environment to environment. That being said, my understanding is that AppRole credentials are also exchanged for tokens, so you should be able to string together a workflow that retrieves the token and then invokes the ssh-renewal. I imagine that something like this might work:

```bash
set -euo pipefail
export VAULT_ADDR=http://127.0.0.1:8200
export VAULT_SSH_SIGN_PATH=ssh/sign/host
export VAULT_TOKEN=`curl  --request POST --data '{"role_id":"988a9df-...","secret_id":"37b74931..."}' ${VAULT_ADDR}/v1/auth/approle/login | jq -r .auth.client_token`
vault-ssh-renew
```

**Comment by FWest98** [comment]
You are absolutely right, my message from above was from my discovery phase. By now I have implemented a custom solution that will also renew the vault token on these machines, but this indeed is different per machine. Thanks for answering anyway!
